"""expand jobs schema + canonical skills tables

Revision ID: 4f5815568044
Revises: b9f20459bfce
Create Date: 2026-06-27 18:38:29.011408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f5815568044'
down_revision: Union[str, Sequence[str], None] = 'b9f20459bfce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_table('job_skills',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    op.add_column('jobs', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('area', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('work_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('career_level_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('exp_years_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('exp_years_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('salary_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('salary_period', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('salary_hidden', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column('jobs', sa.Column('salary_details', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('jobs', sa.Column('job_types', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('jobs', sa.Column('work_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('jobs', sa.Column('keywords_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('jobs', sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_jobs_country_code'), 'jobs', ['country_code'], unique=False)
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_jobs_work_mode'), 'jobs', ['work_mode'], unique=False)
    op.create_unique_constraint('uq_jobs_source_external_id', 'jobs', ['source', 'external_id'])
    # ### end Alembic commands ###

    # Not emitted by autogenerate — restrict work_mode to the Wuzzuf vocabulary.
    op.create_check_constraint(
        'ck_jobs_work_mode',
        'jobs',
        "work_mode IS NULL OR work_mode IN ('on_site', 'remote', 'hybrid')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_jobs_work_mode', 'jobs', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_source_external_id', 'jobs', type_='unique')
    op.drop_index(op.f('ix_jobs_work_mode'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_country_code'), table_name='jobs')
    op.drop_column('jobs', 'expires_at')
    op.drop_column('jobs', 'posted_at')
    op.drop_column('jobs', 'raw_payload')
    op.drop_column('jobs', 'keywords_raw')
    op.drop_column('jobs', 'work_roles')
    op.drop_column('jobs', 'job_types')
    op.drop_column('jobs', 'salary_details')
    op.drop_column('jobs', 'salary_hidden')
    op.drop_column('jobs', 'salary_period')
    op.drop_column('jobs', 'salary_currency')
    op.drop_column('jobs', 'salary_max')
    op.drop_column('jobs', 'salary_min')
    op.drop_column('jobs', 'language')
    op.drop_column('jobs', 'exp_years_max')
    op.drop_column('jobs', 'exp_years_min')
    op.drop_column('jobs', 'career_level_raw')
    op.drop_column('jobs', 'work_mode')
    op.drop_column('jobs', 'area')
    op.drop_column('jobs', 'city')
    op.drop_column('jobs', 'country_code')
    op.drop_column('jobs', 'external_id')
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
