"""add job_tracking and job_tracking_events

Revision ID: b9f20459bfce
Revises: 360fbe5a45e2
Create Date: 2026-06-25 17:45:37.242565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f20459bfce'
down_revision: Union[str, Sequence[str], None] = '360fbe5a45e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('reviewed', 'saved', 'shortlisted', 'applied', 'rejected', 'ignored', name='trackingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_job_tracking_user_job')
    )
    op.create_index(op.f('ix_job_tracking_job_id'), 'job_tracking', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_tracking_user_id'), 'job_tracking', ['user_id'], unique=False)
    op.create_table('job_tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('reviewed', 'saved', 'shortlisted', 'applied', 'rejected', 'ignored', name='trackingstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('reviewed', 'saved', 'shortlisted', 'applied', 'rejected', 'ignored', name='trackingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_tracking_events_job_id'), 'job_tracking_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_tracking_events_user_id'), 'job_tracking_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_tracking_events_user_id'), table_name='job_tracking_events')
    op.drop_index(op.f('ix_job_tracking_events_job_id'), table_name='job_tracking_events')
    op.drop_table('job_tracking_events')
    op.drop_index(op.f('ix_job_tracking_user_id'), table_name='job_tracking')
    op.drop_index(op.f('ix_job_tracking_job_id'), table_name='job_tracking')
    op.drop_table('job_tracking')
    # ### end Alembic commands ###
    # Both tables share the native ``trackingstatus`` enum; drop it once the
    # last referencing table is gone so a later re-upgrade can recreate it.
    sa.Enum(name='trackingstatus').drop(op.get_bind(), checkfirst=True)
